[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ["ds-test/=lib/ds-test/src/", "@openzeppelin/=lib/openzeppelin-contracts/", "@erc725/smart-contracts/=lib/ERC725/implementations/", "solidity-bytes-utils/=lib/solidity-bytes-utils/"]

# See more config options https://github.com/gakonst/foundry/tree/master/config